### ISSUE TITLE
[Suggestion]; Please Create A Config-File 

### ISSUE THREAD

**Issue by Lanse505** [BinaryCrafter/StorageSilo#1]
Hello!

I'd love to have a config file so I can change the Storage Capacity of the Storage Silos.
I'm working on a very intricate and expansive pack and I'd love to feature the mod for Mid-Game Storage however 999 Stacks seems abit much for what I'm going for.

**Comment by BinaryCrafter** [comment]
This will be implemented in a future release, however I have no ETA at this moment

**Comment by BinaryCrafter** [comment]
This feature has now been added with commit ef320cb81e9e306229fe6aa1882018ea3302d963, I'll be pushing a build out to Curse shortly.
