### ISSUE TITLE
crash with StorageSilo-1.2.0

### ISSUE THREAD

**Issue by Badcholo** [BinaryCrafter/StorageSilo#11]
http://pastebin.com/0Kcf3ccf

Installed the mod and it just crashed on startup.

**Comment by Badcholo** [comment]
not your mods fault

**Comment by BinaryCrafter** [comment]
Yeah, I think it's probably QuantumStorage that's causing that, however please reopen if you discover it is connected with StorageSilo and I'll investigate further.

**Comment by Badcholo** [comment]
I downgraded their version and it works, it's not related to storagesilo at all,
Thanks for a great mod.

**Comment by BinaryCrafter** [comment]
Thanks for the confirmation. Appreciated.
