### ISSUE TITLE
Pull from inventory for continuous crafting

### ISSUE THREAD

**Issue by Badcholo** [BinaryCrafter/StorageSilo#12]
These Silos work really well with translocators. i really like em.
Thanks for such a nice mod.

When using the crafting silo allow it to pull from the silos inventory for continuous crafting, such as if i wanted a stack of furnaces. I would just place the crafting recipe and it would continue to give me furnaces until i run out of cobblestone in the silo.

**Comment by BinaryCrafter** [comment]
Thanks for the good suggestions. I'm going to split them into separate issues, so I can address them individually.

**Comment by BinaryCrafter** [comment]
Not going to progress this idea, StorageSilo is like a poor man's version of AE2, it's staying simple.
