### ISSUE TITLE
Drop items on an occupied slot

### ISSUE THREAD

**Issue by BinaryCrafter** [BinaryCrafter/StorageSilo#16]
From @Badcholo: Allow items to be placed into the silo over other items instead of having to scroll down to a empty slot or shift click. Sometimes I forget and I have to place it back in my inventory or scroll.

**Comment by BinaryCrafter** [comment]
Not going to progress this idea, StorageSilo is like a poor man's version of AE2, it's staying simple. Please use shift click.

**Comment by Badcholo** [comment]
I agree it is a vanilla version of AE2 without the tech. That is why i like it so much. I never liked the chest organization. Its not that it would make it so great and wonderful or OP with this feature. It would just get rid of a annoying issue.
