### ISSUE TITLE
Hold Inventory upon breaking

### ISSUE THREAD

**Issue by Badcholo** [BinaryCrafter/StorageSilo#23]
So my 3yrs old got on 1 of my accounts and broke 1 of my silos on a server i created. Unfortunately all the stuff spilled onto the floor lagging the server to a complete stop. I am currently going to try some commands to stop lag and get all the items back into the silo, but i'm kinda disappointed that i might have to run the command /killall all world. we have been running dungeons and such and it would be sucky to lose all our stuff or have someone hop on the server and crash it like so. 

If the silos were capable of holding inventory or if they had storage drives that were inserted so that only a few items or none dropped when broken would be a life saver.

**Comment by Badcholo** [comment]
I was able to type /stoplag in console to get some of the items back, but i lost quite a bit. No worries, its ok. I have now filled up 3 storage silos and was wondering if you would think about making a multiblock structure or a way to connect all the silos to 1 interface?

**Comment by BinaryCrafter** [comment]
Thanks for the info, I've been thinking about ways of preventing this from happening, and will hopefully offer improvements in the 1.8.9 version.

**Comment by Badcholo** [comment]
poop. no more support for 1.7.10? backport maybe, I still see players playing 1.5.2 and mods offering support for them so i don't believe 1.7.10 will be going away any time soon. Plus it will take quite before we figure out what version will be most popular next. Have you any idea on what version will be most popular next?

**Comment by BinaryCrafter** [comment]
I'll provide bug fixes for 1.7.10, but don't plan on adding more features to that branch now. New features will likely be for 1.8.9 only moving forwards. Most mods are now starting to move to 1.8.9, and even FTB have announced that they are no longer providing updates to their 1.7.10 modpacks (except for critical bugs). I expect 1.8.9 will become the popular choice for modded minecraft more and more as the year progresses.

**Comment by Badcholo** [comment]
hmm, i run a kcauldron server. I wonder what will be used for plugins since sponge isn't ready yet.

**Comment by BinaryCrafter** [comment]
This feature request has now been implemented, and will be in the next release of StorageSilo in the following days, however I won't be retrofitting this feature to versions prior to 1.9.4
