### ISSUE TITLE
Why is the mod gone from Curse/Curseforge?

### ISSUE THREAD

**Issue by BrisingrAerowing** [BinaryCrafter/StorageSilo#28]
As per title. The mod is completely gone from Curse and Curseforge. Why?

**Comment by BinaryCrafter** [comment]
Apologies, but this mod is now only available on my website, http://www.binarycraft.uk/. Apologies for any inconvenience this may cause.

**Comment by BrisingrAerowing** [comment]
Ah, OK. Thanks. I did a build for 1.9 myself, although I quickly found that 1.9 does not want to work for me (crashes on crashes on crashes on crashes ad infinitium)

**Comment by BinaryCrafter** [comment]
The binary version available on my site should work, though if it doesn't, please post a stack trace/log and I'll investigate.
